# Site settings
title: Ariescat Blog
SEOTitle: 一只白羊座的傻猫 | Ariescat Blog
header-img: img/header/index.jpg
email: 1275563227@qq.com
description: "Every failure is leading towards success."
keyword: "一只白羊座的傻猫, Blog, Java, Ariescat"
url: "http://ariescat.top/"                 # your host, for absolute URL
baseurl: ""                                 # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Ariescat/ariescat.github.io/"

# Sidebar settings
sidebar: true                               # whether or not using Sidebar.
sidebar-about-description: "不管这一天有多难过，记得认真洗脸冲澡..."
sidebar-avatar: /img/about-BY-gentle.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    Ariescat
jianshu_username:   39035eb3096b
csdn_username:      PingXiaoGai
#weibo_username:     ariescat
#zhihu_username:     ariescat
#facebook_username:  ariescat
#twitter_username:   ariescat




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","bin","Gruntfile.js","package.json","README.md","CNAME","Gemfile*"]
anchorjs: true                  # if you want to customize anchor. check out line:181 of `post.html`
collections:
  docs:
    output: true


# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                    # use Github Flavored Markdown !important



# 评论系统

# Gitalk
gitalk:
  enable: false                  #是否开启Gitalk评论
  clientID: 1b762e3fb7d766fefa60                            #生成的clientID
  clientSecret: c011a01671ccb88ba8640c4e488014b12ca41cbf    #生成的clientSecret
  repo: ariescat.github.io      #仓库名称
  owner: ariescat               #github用户名
  admin: ariescat
  distractionFreeMode: true     #是否启用类似FB的阴影遮罩

# Valine
valine:
  enable: true                  #是否开启Valine评论
  appId: 8sgcuqXs6ecrgY74WuVkQXCJ-gzGzoHsz                  #生成的appId
  appKey: QXoMCzb8TFMV0DBzDNXkcvxa                          #生成的appKey
  placeholder: '来啊，快活啊 ฅʕ•̫͡•ʔฅ  |  支持QQ头像和昵称哦~'    #评论框占位提示符
  enableQQ: true                #是否启用昵称框自动获取QQ昵称和QQ头像
  recordIP: true                #是否记录评论者IP


# Twikoo
twikoo:
  enable: false
  envId: blog-5gkhnwtme934ae46  # CloudBase的环境id


# Aplayer
aplayer:
  enable: true


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: ce850ecbd046e90ec9fce2f9d52bcac5

# Google Analytics
# ga_track_id: 'UA-90855596-1'    # Format: UA-xxxxxx-xx
# ga_domain: ariescat.top         # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto



# Featured Tags
featured-tags: true             # 是否使用首页标签
featured-condition-size: 0      # 相同标签数量大于这个数，才会出现在首页，默认为0



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Links
links: [
{
  title: "简书",
  href: "https://www.jianshu.com/"
},
{
  title: "知乎",
  href: "https://www.zhihu.com/"
},
{
  title: "掘金",
  href: "https://juejin.im/"
}
]